# Generated by Django 6.0.4 on 2026-05-07 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_iva', models.BooleanField(default=True)),
                ('descripcion_adicional', models.CharField(max_length=250)),
            ],
        ),
    ]
