# Generated by Django 6.0.4 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_adicional',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
