# Generated by Django 6.0.4 on 2026-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion_id', models.CharField(choices=[('04', 'RUC'), ('05', 'CÉDULA'), ('06', 'PASAPORTE'), ('07', 'VENTA AL CONSUMIDOR FINAL'), ('08', 'IDENTIFICACION DEL EXTERIOR')], default='05', max_length=2)),
                ('identificacion', models.CharField(default='9999999999', max_length=13)),
                ('razon_social', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=60)),
            ],
        ),
    ]
