# Generated by Django 6.0.4 on 2026-05-07 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_id_clientes_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
