# Generated by Django 5.2 on 2026-05-13 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion_alter_cliente_telefono'),
        ('empresas', '0005_alter_empresa_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_emision', models.DateTimeField(default=None)),
                ('clave_acceso', models.CharField(max_length=250)),
                ('secuencial', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xml', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('ride_pdf', models.BinaryField(blank=True, null=True)),
                ('autorizacion_numero', models.CharField(blank=True, max_length=250, null=True)),
                ('autorizacion_fecha', models.DateTimeField(blank=True, default=None, null=True)),
                ('sri_estado', models.CharField(blank=True, max_length=250, null=True)),
                ('sri_mensajes', models.JSONField(blank=True, null=True)),
                ('sri_fecha_envio', models.DateTimeField(blank=True, default=None, null=True)),
                ('sri_fecha_respuesta', models.DateTimeField(blank=True, default=None, null=True)),
                ('datos_originales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empresa_emisora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa_emisora_id', 'secuencial')},
            },
        ),
    ]
