# Generated by Django 6.0.4 on 2026-05-08 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ruc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=250)),
                ('nombre_comercial', models.CharField(max_length=250)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion_matriz', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion_establecimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('codigo_establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('tipo_ambiente', models.IntegerField(choices=[(1, 'Produccion'), (2, 'Pruebas')], default=1)),
                ('tipo_emision', models.IntegerField(choices=[(1, 'Normal')], default=1)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('contribuyente_especial', models.CharField(blank=True, max_length=250, null=True)),
                ('email_notificacion', models.EmailField(blank=True, max_length=60, null=True)),
                ('certificate', models.CharField(blank=True, max_length=250, null=True)),
                ('certificate_password', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
