# Generated by Django 5.2 on 2026-05-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_empresa_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='empresas.empresa'),
        ),
    ]
