# Generated by Django 5.2 on 2026-05-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_certificado_empresa_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('empresa_id', 'certificate')},
        ),
        migrations.AddField(
            model_name='certificado',
            name='_enc_certificate_password',
            field=models.TextField(blank=True, db_column='cerificate_password', null=True),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificate_password',
        ),
    ]
