# Generated by Django 5.2 on 2026-05-11 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_certificado_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('user_id', 'ruc')},
        ),
    ]
